# Generated by Django 3.1.1 on 2021-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagecustomisation_home_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarCustomisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(max_length=25)),
                ('link_2', models.CharField(max_length=25)),
                ('link_3', models.CharField(max_length=25)),
                ('link_4', models.CharField(max_length=25)),
            ],
        ),
    ]
