# Generated by Django 3.1.1 on 2021-05-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navbarcustomisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagecustomisation',
            options={'verbose_name': 'Home Page'},
        ),
    ]
